// {
//   "@odata.count": 20,
const records = [
  {
    id: 2,
    name: "Kayal",
    email: "pkayal9999@example.com",
    address: "123 ten",
    country: "USA",
    phone: "1234567",
    specialistsDiscoverable: true,
    matrxUnits: 4,
    includeInAnalyticsReport: true,
  },
  {
    id: 4,
    name: "ust",
    email: "bumbledental@example.com",
    address: "43",
    country: "Canada",
    phone: "2",
    specialistsDiscoverable: true,
    matrxUnits: 6,
    includeInAnalyticsReport: true,
  },
  {
    id: 6,
    name: "tan",
    email: "rantanfan@example.com",
    address: "address",
    country: "Canada",
    phone: "123",
    specialistsDiscoverable: true,
    matrxUnits: 5,
    connectedProgram: true,
  },
  {
    id: 8,
    name: "ZephyrSleep",
    email: "edmontonpractitioner1@example.com",
    address: "",
    country: "USA",
    phone: "1111111",
    specialistsDiscoverable: true,
    matrxUnits: 6,
    connectedProgram: false,
  },
  {
    id: 9,
    name: "ZST",
    email: "zephyrv3portal@example.com",
    address: "",
    country: "Canada",
    phone: "21111111",
    specialistsDiscoverable: false,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 12,
    name: "ChicaSleep",
    email: "chicagomatrxplus1@example.com",
    address: "",
    country: "USA",
    phone: "",
    specialistsDiscoverable: true,
    matrxUnits: 0,
    connectedProgram: true,
  },
  {
    id: 19,
    name: "jungle",
    email: "ana@example.com",
    address: "",
    country: "Canada",
    phone: "",
    specialistsDiscoverable: false,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 24,
    name: "Zephyr Sleep Technologies Inc.",
    email: "hv@example.com",
    address: "w",
    country: "Canada",
    phone: "Smile",
    specialistsDiscoverable: false,
    matrxUnits: 1,
    connectedProgram: false,
  },
  {
    id: 29,
    name: "Zephyr",
    email: "android@example.com",
    address: "",
    country: "USA",
    phone: "403000000000",
    specialistsDiscoverable: false,
    matrxUnits: 7,
    connectedProgram: true,
  },
  {
    id: 40,
    name: "migration",
    email: "windows@example.com",
    address: "",
    country: "Canada",
    phone: "1800000011",
    specialistsDiscoverable: false,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 49,
    name: "ZST",
    email: "winTest@example.com",
    address: "",
    country: "Canada",
    phone: "4031111111",
    specialistsDiscoverable: false,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 59,
    name: "Random's Practice",
    email: "fcrosbie@example.com",
    address: "",
    country: "Canada",
    phone: "155555555",
    specialistsDiscoverable: false,
    matrxUnits: 11,
    connectedProgram: true,
  },
  {
    id: 66,
    name: "Trevor's Practice",
    email: "tle@example.com",
    address: "111111",
    country: "USA",
    phone: "123123123",
    specialistsDiscoverable: false,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 67,
    name: "New Practice 1",
    email: "0000001386758590@example.com",
    address: "1234 Fake Street",
    country: "Canada",
    phone: "555-555-4444",
    specialistsDiscoverable: true,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 68,
    name: "New Practice 1",
    email: "0000002008553031@example.com",
    address: "1234 Fake Street",
    country: "Canada",
    phone: "555-555-4444",
    specialistsDiscoverable: true,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 69,
    name: "New Practice 1",
    email: "0000001164042860@example.com",
    address: "1234 Fake Street",
    country: "Canada",
    phone: "555-555-4444",
    specialistsDiscoverable: true,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 70,
    name: "New Practice 1",
    email: "0000001973611830@example.com",
    address: "1234 Fake Street",
    country: "Canada",
    phone: "555-555-4444",
    specialistsDiscoverable: true,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 71,
    name: "New Practice 1",
    email: "0000001243424747@example.com",
    address: "1234 Fake Street",
    country: "Canada",
    phone: "555-555-4444",
    specialistsDiscoverable: true,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 72,
    name: "HK",
    email: "Hk@example.com",
    address: "bela bela",
    country: "Canada",
    phone: "4035614081",
    specialistsDiscoverable: true,
    matrxUnits: 1,
    connectedProgram: true,
  },
  {
    id: 73,
    name: "New Practice 1",
    email: "0000000663053045@example.com",
    address: "1234 Fake Street",
    country: "Canada",
    phone: "555-555-4444",
    specialistsDiscoverable: true,
    matrxUnits: 1,
    connectedProgram: true,
  },
];

export function getRecords() {
  return records;
}

export function getRecord(id) {
  return records.find((r) => r.id === id);
}
